baseURL = 'https://fronzec.github.io/'
languageCode = 'en-us'
title = "Eduardo Flores"
theme = "hugo-theme-m10c"


[pagination]
  pagerSize = 6

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1


[params]
  author = "Eduardo Flores"
  description = '''
  Hello! I'm a Software Engineer, working mainly with backend systems. I'm proficient using Java, Go, and Rust.

  '''
  menu_item_separator = " - "
  avatar = "/fronzec-01.jpg"
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/gohugoio"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/fronzec/"



  # Default theme
  # [params.style]
  #   darkestColor = "#242930"
  #   darkColor = "#353b43"
  #   lightColor = "#afbac4"
  #   lightestColor = "#ffffff"
  #   primaryColor = "#57cc8a"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"